const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_PROCESSING: 'EMAIL_SIGN_IN_PROCESSING',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_PROCESSING: 'SIGN_UP_PROCESSING',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    GET_USER_START: 'GET_ALL_USER_START',
    GET_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_USER_PROCESSING: 'GET_ALL_USER_PROCESSING',
    GET_USER_FAILURE: 'GET_ALL_USER_FAILURE',

    GET_ONE_USER_START: 'GET_ONE_USER_START',
    GET_ONE_USER_SUCCESS: 'GET_ONE_USER_SUCCESS',
    GET_ONE_USER_PROCESSING: 'GET_ONE_USER_PROCESSING',
    GET_ONE_USER_FAILURE: 'GET_ONE_USER_FAILURE',

    UPDATE_USER_START: 'UPDATE_USER_START',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_PROCESSING: 'UPDATE_USER_PROCESSING',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

    UPDATE_REQUIRED_USER_START: 'UPDATE_REQUIRED_USER_START',
    UPDATE_REQUIRED_USER_SUCCESS: 'UPDATE_REQUIRED_USER_SUCCESS',
    UPDATE_REQUIRED_USER_PROCESSING: 'UPDATE_REQUIRED_USER_PROCESSING',
    UPDATE_REQUIRED_USER_FAILURE: 'UPDATE_REQUIRED_USER_FAILURE',

    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_PROCESSING: 'DELETE_USER_PROCESSING',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

    //MESSAGES
    GET_MESSAGE_SENDER_START: 'GET_MESSAGE_SENDER_START',
    GET_MESSAGE_SENDER_SUCCESS: 'GET_MESSAGE_SENDER_SUCCESS',
    GET_MESSAGE_SENDER_PROCESSING: 'GET_MESSAGE_SENDER_PROCESSING',
    GET_MESSAGE_SENDER_FAILURE: 'GET_MESSAGE_SENDER_FAILURE',
    // FEATURES

    GET_CATEGORY_SERVICE_START: 'GET_CATEGORY_SERVICE_START',
    GET_CATEGORY_SERVICE_SUCCESS: 'GET_CATEGORY_SERVICE_SUCCESS',
    GET_CATEGORY_SERVICE_PROCESSING: 'GET_CATEGORY_SERVICE_PROCESSING',
    GET_CATEGORY_SERVICE_FAILURE: 'GET_CATEGORY_SERVICE_FAILURE',

    REGISTER_CATEGORY_SERVICE_START: 'REGISTER_CATEGORY_SERVICE_START',
    REGISTER_CATEGORY_SERVICE_SUCCESS: 'REGISTER_CATEGORY_SERVICE_SUCCESS',
    REGISTER_CATEGORY_SERVICE_PROCESSING: 'REGISTER_CATEGORY_SERVICE_PROCESSING',
    REGISTER_CATEGORY_FAILURE: 'REGISTER_CATEGORY_SERVICE_FAILURE',

    DELETE_CATEGORY_SERVICE_START: 'DELETE_CATEGORY_SERVICE_START',
    DELETE_CATEGORY_SERVICE_SUCCESS: 'DELETE_CATEGORY_SERVICE_SUCCESS',
    DELETE_CATEGORY_SERVICE_PROCESSING: 'DELETE_CATEGORY_SERVICE_PROCESSING',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_SERVICE_FAILURE',

    GET_SERVICE_START: 'GET_SERVICE_START',
    GET_SERVICE_SUCCESS: 'GET_SERVICE_SUCCESS',
    GET_SERVICE_PROCESSING: 'GET_SERVICE_PROCESSING',
    GET_SERVICE_FAILURE: 'GET_SERVICE_FAILURE',

    REGISTER_SERVICE_START: 'REGISTER_SERVICE_START',
    REGISTER_SERVICE_SUCCESS: 'REGISTER_SERVICE_SUCCESS',
    REGISTER_SERVICE_PROCESSING: 'REGISTER_SERVICE_PROCESSING',
    REGISTER_FAILURE: 'REGISTER_SERVICE_FAILURE',

    DELETE_SERVICE_START: 'DELETE_SERVICE_START',
    DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
    DELETE_SERVICE_PROCESSING: 'DELETE_SERVICE_PROCESSING',
    DELETE_SERVICE_FAILURE: 'DELETE_SERVICE_FAILURE',

    SEND_MESSAGE_START: 'SEND_MESSAGE_START',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_PROCESSING: 'SEND_MESSAGE_PROCESSING',
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',

    GET_MESSAGE_START: 'GET_MESSAGE_START',
    GET_MESSAGE_SUCCESS: 'GET_MESSAGE_SUCCESS',
    GET_MESSAGE_PROCESSING: 'GET_MESSAGE_PROCESSING',
    GET_MESSAGE_FAILURE: 'GET_MESSAGE_FAILURE',

    ADD_FRIEND_START: 'ADD_FRIEND_START',
    ADD_FRIEND_SUCCESS: 'ADD_FRIEND_SUCCESS',
    ADD_FRIEND_PROCESSING: 'ADD_FRIEND_PROCESSING',
    ADD_FRIEND_FAILURE: 'ADD_FRIEND_FAILURE',
  };
  export default UserActionTypes;
  